trigger:
- new-branch

pool:
  vmImage: ubuntu-latest

stages:
- stage: FirstStage
  displayName: "First stage"
  jobs:
  - job: FirstJob
    displayName: "First job"
    steps:
    - script: echo "Hello from Azure DevOps"
      displayName: "Echo Hello"
