trigger:
- new-branch

pool:
  vmImage: ubuntu-latest

stages:
- stage: FirstStage
  displayName: "First stage1111"
  jobs:
  - job: FirstJob
    displayName: "First job111"
    steps:
    - script: echo "Hello from Azure DevOps"
      displayName: "Echo Hello"
